#!/bin/sh
# ---------------------------------------------------------------------------------------------------------------------
# SPDX-License-Identifier: GPL-2.0
# ---------------------------------------------------------------------------------------------------------------------
#
# Copyright 2024 Siemens
#
# This file is licensed under the terms of the GNU General Public License
# version 2.  This program  is licensed "as is" without any warranty of any
# kind, whether express or implied.

packages="python39 \
          python3-setuptools \
          patch diffstat git bzip2 tar \
          gzip gawk chrpath wget cpio perl file which \
          rsync rpcgen \
          zstd lz4"

if lsb_release -ds | grep -Pq '(?:Red Hat Enterprise|Rocky) Linux release 8'; then
    # Following packages require sourcing their environment which is done through
    # setup-environment script:
    # - `source scl_source enable gcc-toolset-9`
    # - `source scl_source enable make43`
    packages+=" make43 gcc-toolset-9 scl-utils"
else
    packages+=" make gcc gcc-c++"
fi

set -e

if [ "$(id -u)" != "0" ]; then
    echo "Verifying access to sudo, please enter your password if prompted."
    if ! sudo -v; then
        echo >&2 "Could not use sudo, exiting"
        exit 1
    fi
    exec sudo "$0" "$@"
fi

# Enable required repo's to get install rpcgen package

echo "Enabling any required repos"
if [ `lsb_release -is` = 'RedHatEnterprise' ]; then
    subscription-manager repos --enable "codeready-builder-for-rhel-`lsb_release -rs | cut -d. -f1`-`arch`-rpms"
elif [ `lsb_release -is` = 'Rocky' ]; then
    dnf config-manager --set-enabled powertools
fi

echo "Installing packages required to build Flex OS"
dnf install --assumeyes "$@" $packages || {
    echo >&2 "Error installing our required packages, aborting"
    exit 1
}

# Add symbolic link for the required version of python on following OS releases
if lsb_release -ds | grep -Pq '(?:Red Hat Enterprise|Rocky) Linux release 8'; then
    ln -sfn /usr/bin/python3.9 /usr/local/bin/python3
fi

echo "Setup complete"
