#!/bin/sh
# ---------------------------------------------------------------------------------------------------------------------
# SPDX-License-Identifier: GPL-2.0
# ---------------------------------------------------------------------------------------------------------------------
#
# Copyright 2022 Siemens
#
# This file is licensed under the terms of the GNU General Public License
# version 2.  This program  is licensed "as is" without any warranty of any
# kind, whether express or implied.

echo "Verifying access to sudo, please enter your password if prompted."
if [ "$(id -u)" -ne 0 ]; then
    SUDO=sudo
    $SUDO -v
    if [ $? -ne 0 ]; then
        echo >&2 "Could not use sudo, exiting"
        exit 1
    fi
else
    SUDO=
fi

PKGS="$PKGS ubuntu-minimal ubuntu-standard make gcc g++ patch diffstat texinfo texi2html cvs subversion bzip2 tar gzip gawk chrpath libncurses5-dev git-core lsb-release python3 python3-setuptools xvfb x11-utils rsync zstd liblz4-tool"

# These are needed for the qemu-native build
PKGS="$PKGS libgl1-mesa-dev libglu1-mesa-dev libsdl1.2-dev"

# This is helpful to write images, and is in our documentation
PKGS="$PKGS bmap-tools"

echo "Installing packages required to build Innexis Linux"
$SUDO apt-get update
$SUDO apt-get -y install $PKGS

if [ "$(uname -m)" = "x86_64" ]; then
    $SUDO dpkg --add-architecture i386
    $SUDO apt-get -y install libc6-dev-i386
    $SUDO apt-get -y install libncurses5:i386
fi

echo "Generating the en_US.UTF-8 locale"
$SUDO locale-gen en_US.UTF-8

# Workaround for ubuntu-24 issue [Allow bitbake to create user namespace](https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2056555)
if grep -Pq '^VERSION_ID=(?:|")24\.' /etc/os-release; then
    echo "Adding Bitbake's AppArmor Profile to associate it with User Namespace profile"
    echo "NOTE: This is a workaround for Ubuntu bug (https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2056555)"
    echo "which gives unconfined access to bitbake binary. You may review the AppArmor Profile for Bitbake available"
    echo "here: /etc/apparmor.d/bitbake"
    $SUDO tee /etc/apparmor.d/bitbake > /dev/null <<'EOF'
abi <abi/4.0>,
include <tunables/global>
profile bitbake /**/bitbake/bin/bitbake flags=(unconfined) {
        userns,
}
EOF
    # Reload AppArmor Profile
    $SUDO apparmor_parser -r /etc/apparmor.d/bitbake
fi

echo "Setup complete"
